"""LLM-backed contextualizer for contextual retrieval.

Provider-agnostic: it depends only on the ``ChatModel`` port, so the situating
blurbs can be generated by any configured provider (OpenAI-compatible, Gemini,
local server). Whether/which provider does prompt caching is the adapter's
concern, not ours.
"""

from __future__ import annotations

from ragu.core import Document
from ragu.ports.llm import ChatMessage, ChatModel

_SYSTEM = (
    "You situate a chunk within its source document for retrieval. "
    "Reply with 1-2 short sentences of context only — no preamble, no quotes."
)

_PROMPT = (
    "<document>\n{document}\n</document>\n\n"
    "Here is a chunk from that document:\n\n<chunk>\n{chunk}\n</chunk>\n\n"
    "Give a concise context that situates this chunk within the document, to "
    "improve search retrieval. Answer with the context only."
)


class LLMContextualizer:
    def __init__(self, model: ChatModel, *, max_tokens: int = 128) -> None:
        self._model = model
        self._max_tokens = max_tokens

    async def contextualize(self, document: Document, chunk_text: str) -> str:
        messages = [
            ChatMessage(role="system", content=_SYSTEM),
            ChatMessage(
                role="user",
                content=_PROMPT.format(document=document.content, chunk=chunk_text),
            ),
        ]
        return await self._model.complete(messages, max_tokens=self._max_tokens)
